services:
  backend:
    build: ./backend
    container_name: laravel_backend
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html

  frontend:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: