services:

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel

  backend:
    container_name: laravel_app
    build:
      context: ./backend
    depends_on:
      - db
    restart: always
    ports:
      - "8001:80"
    develop:
      watch:
        - path : ./backend
          target: /var/www/html
          action: sync
          ignore: 
            - vendor
        - path : ./backend/composer.json
          target: /var/www/html/composer.json
          action: sync+restart

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - backend
